version: '3.8'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    restart: always
    command: sh -c "npm run migrate:up && npm run dev"
    volumes:
      - static_volume:/home/app/backend/public
      - ./backend:/home/app/backend
      - ./.env:/home/app/.env
    expose:
      - 3000
    env_file:
      - ./.env
    depends_on:
      - db
    links:
      - db:db
    networks:
      - snapshortnetwork
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/home/app/backend/public
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - web
    links:
      - web:web
    networks:
      - snapshortnetwork
  db:
    image: postgres:16.1-alpine
    restart: always
    user: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgresql/:/docker-entrypoint-initdb.d/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - snapshortnetwork

networks:
  snapshortnetwork:
      driver: bridge

volumes:
  postgres_data:
  static_volume:
